logging:
  file:
    path: ./logs # 相对于项目根路径
    name: ${logging.file.path}/application.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/%d{yyyy-MM-dd}.%i.log
      max-file-size: 32MB
      max-history: 16 # 单位为天
  level:
    org.kagura: debug
    org.springframework:
      web: # 响应式网络层日志
        server.adapter.HttpWebHandlerAdapter: debug # 请求/响应状态
        reactive.function.server.support.RouterFunctionMapping: debug # 请求映射的路由

spring:
  application:
    name: springai
  webflux:
    base-path: /api
    problemdetails:
      enabled: true
  config:
    import:
      - optional:file:.env.local[.properties] # 以 .properties 文件的格式读取 .env.local，模拟环境变量读取
  ai:
    ollama:
      embedding:
        model: bge-m3:567m
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        model: deepseek-v4-pro
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
      client:
        enabled: false
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1024
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: postgres
    password: ${DATABASE_PASSWORD}
