logging:
  file:
    path: ./logs # 相对于项目根路径
    name: ${logging.file.path}/application.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/%d{yyyy-MM-dd}.%i.log
      max-file-size: 32MB
      max-history: 16 # 单位为天
  level:
    org.kagura: debug
    org.springframework:
      web.servlet: debug

spring:
  application:
    name: springai
  mvc:
    servlet:
      path: /api
    problemdetails:
      enabled: true
  config:
    import:
      - optional:file:.env.local[.properties] # 以 .properties 文件的格式读取 .env.local，模拟环境变量读取
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        model: deepseek-v4-pro
