/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

group = "org.kagura"
version = "0.0.1-SNAPSHOT"

repositories {
    maven { url = uri("https://repo.huaweicloud.com/repository/maven/") }
    mavenCentral()
}

dependencies {
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
    testCompileOnly(libs.lombok)
    testAnnotationProcessor(libs.lombok)
    testRuntimeOnly(libs.junit.platform.launcher)
    implementation(libs.spring.boot.starter.webflux)
    testImplementation(libs.spring.boot.starter.webflux.test)
    implementation(platform(libs.spring.ai.bom))
    implementation(libs.spring.ai.starter.model.ollama)
    implementation(libs.spring.ai.starter.model.deepseek)
    implementation(libs.spring.ai.starter.model.chat.memory.repository.jdbc)
    implementation(libs.spring.ai.starter.vector.store.pgvector)
    implementation(libs.spring.ai.advisors.vector.store)
    implementation(libs.spring.ai.rag)
}

tasks.withType<Test> {
    useJUnitPlatform()
}
